# Generated by Django 3.2.8 on 2021-10-27 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthApp', '0002_advisor_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='advisor_book',
            new_name='advisor_booking',
        ),
    ]
