# Generated by Django 3.2.8 on 2021-10-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_rename_advisor_book_advisor_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor_booking',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthApp.advisor'),
        ),
    ]
